version: 2.1

orbs:
  heroku: circleci/heroku@0.0.8

defaults: &defaults
  working_directory: /home/circleci/project
  docker:
    - image: counterfactual/circleci-environment:latest

save_code: &save_code
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .git

save_dep: &save_dep
  save_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

restore_code: &restore_code
  restore_cache:
    key: code-{{ .Revision }}

restore_dep: &restore_dep
  restore_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}

jobs:
  build:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *save_code

      - <<: *restore_dep
      - run:
          name: "yarn --frozen-lockfile"
          command: yarn --frozen-lockfile

      - run: yarn build

      - <<: *save_dep

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build

  run-non-playground-tests:
    docker:
      - image: circleci/node:10.15.3
        environment:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_USER: postgres
          POSTGRES_DATABASE: postgres
          POSTGRES_PORT: 5432

      - image: circleci/postgres:9.6.14-alpine
        environment:
          POSTGRES_USER: postgres

    steps:
      - <<: *restore_code
      - checkout

      - <<: *restore_dep
      - run: sudo npm i -g yarn@1.12.3 # because docker image uses 1.13.0

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Run Non-Playground-related tests
          command: yarn test:ci-non-playground

  run-playground-tests:
    <<: *defaults
    docker:
      - image: circleci/node:10.15.3-browsers
    steps:
      - <<: *restore_code

      - checkout

      - <<: *restore_dep

      - run: sudo npm i -g yarn@1.12.3 # because docker image uses 1.13.0

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Run Simple Hub Server tests
          command: cd packages/simple-hub-server && yarn test:ci
      - run:
          name: Run High Roller tests
          command: cd packages/dapp-high-roller && yarn test
      - run:
          name: Run Tic-Tac-Toe tests
          command: cd packages/dapp-tic-tac-toe && yarn test

  greenboard-prepare:
    <<: *defaults
    docker:
      - image: circleci/node:8.15
    steps:
      - <<: *restore_code

      - checkout

      - <<: *restore_dep

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Clone Metamask fork
          command: git clone --depth 1 --single-branch --branch joel/for-wallet-ui git@github.com:prototypal/metamask-extension ./metamask
      - run:
          name: Install Gulp
          command: npm i -g gulp-cli
      - run:
          name: Update CF.js IIFE
          command: cp packages/cf.js/dist/index-iife.js metamask/app/vendor/counterfactual/node/cf.js.iife.js
      - run:
          name: Update Firebase Client IIFE
          command: cp packages/firebase-client/dist/index.iife.js metamask/app/vendor/counterfactual/node/firebase-client.iife.js
      - run:
          name: Update Node IIFE
          command: cp packages/node/dist/index.iife.js metamask/app/vendor/counterfactual/node/node.iife.js
      - run:
          name: Install dependencies
          command: cd metamask && npm ci
      - run:
          name: Build Metamask extension with CF IIFEs
          command: cd metamask && gulp build

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build
            - metamask/*/dist

  greenboard-run:
    <<: *defaults
    docker:
      - image: circleci/node:10.15.3-browsers
    steps:
      - <<: *restore_code

      - checkout

      - <<: *restore_dep

      - attach_workspace:
          at: /home/circleci/project

      - run: sudo npm i -g yarn@1.12.3 # because docker image uses 1.13.0

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - run:
          name: Run X virtual framebuffer for Selenium
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true

      - run:
          name: Copy Metamask dist into extension
          command: mkdir packages/greenboard/extension && cp metamask/dist/chrome packages/greenboard/extension

      - run:
          name: Open Wallet UI
          command: cd packages/wallet-ui && yarn start
          background: true

      - run:
          name: Raise database
          command: cd packages/simple-hub-server && docker-compose up -d

      - run:
          name: Open Simple Hub Server
          command: cd packages/simple-hub-server && yarn start

      - run:
          name: Run Greenboard (E2E tests)
          command: cd packages/greenboard && yarn test

  run-tslint:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout

      - <<: *restore_dep

      - attach_workspace:
          at: /home/circleci/project

      - run: npm i -g yarn@1.12.3 # because docker image uses 1.13.0

      - run: yarn lint

  ensure-updated-lockfiles:
    <<: *defaults
    steps:
      - <<: *restore_code

      - checkout

      - <<: *restore_dep

      - attach_workspace:
          at: /home/circleci/project

      - run: apt-get install -y jq # using this to mutate package.json

      - run: npm i -g yarn@1.12.3 # because docker image uses 1.13.0

      - run:
          name: Check root yarn.lock
          command: yarn --frozen-lockfile

  publish-to-npm:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout

      - <<: *restore_dep
      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Add NPM_TOKEN auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - run:
          name: Publish any updated packages to npm
          command: yarn run publish

workflows:
  run-tests:
    jobs:
      - build

      - run-tslint:
          requires:
            - build

      - run-non-playground-tests:
          requires:
            - build

      - run-playground-tests:
          requires:
            - build

      - greenboard-prepare:
          requires:
            - build

      - greenboard-run:
          requires:
            - build
            - greenboard-prepare

      - ensure-updated-lockfiles:
          requires:
            - build

      - publish-to-npm:
          requires:
            - build
            - ensure-updated-lockfiles
            - run-non-playground-tests
            - run-playground-tests
            - run-tslint
          filters:
            branches:
              only: master

      - heroku/deploy-via-git:
          app-name: simple-hub-server-staging
          requires:
            - publish-to-npm
          filters:
            branches:
              only: master

      - heroku/deploy-via-git:
          app-name: hr-bot-staging
          requires:
            - publish-to-npm
          filters:
            branches:
              only: master

      - heroku/deploy-via-git:
          app-name: ttt-bot-staging
          requires:
            - publish-to-npm
          filters:
            branches:
              only: master
