version: 2.1

orbs:
  heroku: circleci/heroku@0.0.5

defaults: &defaults
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node:10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: cat packages/*/package.json yarn.lock | shasum > .dependencies_checksum

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn
      - run: yarn build

      - save_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build

  run-tests:
    <<: *defaults
    steps:
      - checkout
      - run: cat packages/*/package.json yarn.lock | shasum > .dependencies_checksum

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Run Non-Playground-related tests
          command: yarn test:ci-non-playground

  run-playground-tests:
    <<: *defaults
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: cat packages/*/package.json yarn.lock | shasum > .dependencies_checksum

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Run Playground tests
          command: cd packages/playground && yarn test
      - run:
          name: Run Playground Server tests
          command: cd packages/playground-server && yarn test:ci
      - run:
          name: Run High Roller tests
          command: cd packages/dapp-high-roller && yarn test
      - run:
          name: Run Tic-Tac-Toe tests
          command: cd packages/dapp-tic-tac-toe && yarn test

  run-tslint:
    <<: *defaults
    steps:
      - checkout
      - run: cat packages/*/package.json yarn.lock | shasum > .dependencies_checksum

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - attach_workspace:
          at: /home/circleci/project

      - run: yarn lint

  publish-to-npm:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Publish any updated packages to npm
          command: yarn run publish

workflows:
  run-tests:
    jobs:
      - build

      - run-tslint:
          requires:
            - build

      - run-tests:
          requires:
            - build

      - run-playground-tests:
          requires:
            - build

      - heroku/deploy-via-git:
          requires:
            - build
            - run-tests
            - run-playground-tests
            - run-tslint
          filters:
            branches:
              only: master

      - publish-to-npm:
          requires:
            - build
            - run-tests
            - run-playground-tests
            - run-tslint
          filters:
            branches:
              only: master
