version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/contracts/node_modules
            - packages/iframe-wallet-poc/node_modules
            - packages/machine/node_modules
            - packages/cf.js/node_modules

  run-tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn build
      - run:
          name: "Run ganache"
          command: yarn ganache:ci
          background: true
      - run:
          name: "Run playground webpack-dev-server"
          command: cd packages/playground && yarn serve
          background: true
      - run: cd packages/contracts/ && yarn migrate
      - run: yarn test

  run-tslint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn lint

workflows:
  version: 2
  run-tests:
    jobs:
      - build
      - run-tslint:
          requires:
            - build
      - run-tests:
          requires:
            - build
