version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: solc-0.5.2
      - run:
          name: "Downloading solc binary"
          command: |
            test ! -e /usr/local/bin/solc && \
            sudo wget https://github.com/ethereum/solidity/releases/download/v0.5.2/solc-static-linux -O /usr/local/bin/solc && \
            sudo chmod +x /usr/local/bin/solc
      - save_cache:
          key: solc-0.5.2
          paths:
            - /usr/local/bin/solc
      - run:
          name: "Generating dependencies checksum"
          command: cat packages/*/package.json | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
      - run: yarn
      - run: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build

  run-tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cat packages/*/package.json | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn test:ci-non-playground

  run-playground-tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: cat packages/*/package.json | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
      - attach_workspace:
          at: /home/circleci/project
      - run: cd packages/playground && yarn test
      - run: cd packages/dapp-high-roller && yarn test

  run-tslint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cat packages/*/package.json | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn lint

workflows:
  version: 2
  run-tests:
    jobs:
      - build
      - run-tslint:
          requires:
            - build
      - run-tests:
          requires:
            - build
      - run-playground-tests:
          requires:
            - build
