version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cat packages/*/package.json | shasum > .dependencies_checksum
      - run: mkdir -p /tmp/workspace
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
      - run: yarn
      - run: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - packages/*/dist
            - packages/*/build

  run-tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cat packages/*/package.json | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
      - attach_workspace:
          at: /tmp/workspace
      - run: yarn # symlink packages' node_modules
      - run: yarn test:ci-non-playground

  run-playground-tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: cat packages/*/package.json | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
      - attach_workspace:
          at: /tmp/workspace
      - run: yarn # symlink packages' node_modules
      - run: cd packages/playground && yarn test
      - run: cd packages/dapp-high-roller && yarn test

  run-tslint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cat packages/*/package.json | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
      - attach_workspace:
          at: /tmp/workspace
      - run: yarn lint

workflows:
  version: 2
  run-tests:
    jobs:
      - build
      - run-tslint:
          requires:
            - build
      - run-tests:
          requires:
            - build
      - run-playground-tests:
          requires:
            - build
