version: 2.1

orbs:
  heroku: circleci/heroku@0.0.5

defaults: &defaults
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node:10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: cat packages/*/package.json yarn.lock | shasum > .dependencies_checksum

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run:
          name: "Install solc binary"
          command: |
            # install CMake and Boost prerequisite first
            wget http://www.cmake.org/files/v3.13/cmake-3.13.4.tar.gz
            tar -xvzf cmake-3.13.4.tar.gz
            cd cmake-3.13.4
            sudo ./configure --prefix=/opt/cmake & make & make install
            /opt/cmake/bin/cmake -v
            cd ../
            wget https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.7z.tar.gz
            tar -xvzf boost_1_69_0.7z.tar.gz
            cd boost_1_69_0.7z
            sudo ./bootstrap.sh
            sudo ./b2 --with=all -j 2 install

            git clone --recursive https://github.com/ethereum/solidity.git
            cd solidity
            sudo chmod +x ./scripts/*.sh
            ./scripts/install_deps.sh & ./scripts/build.sh

      - run: yarn --frozen-lockfile
      - run: yarn build

      - save_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build

  run-tests:
    <<: *defaults
    steps:
      - checkout
      - run: cat packages/*/package.json yarn.lock | shasum > .dependencies_checksum

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Run Non-Playground-related tests
          command: yarn test:ci-non-playground

  run-playground-tests:
    <<: *defaults
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: cat packages/*/package.json yarn.lock | shasum > .dependencies_checksum

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Run Playground tests
          command: cd packages/playground && yarn test
      - run:
          name: Run Playground Server tests
          command: cd packages/playground-server && yarn test:ci
      - run:
          name: Run High Roller tests
          command: cd packages/dapp-high-roller && yarn test
      - run:
          name: Run Tic-Tac-Toe tests
          command: cd packages/dapp-tic-tac-toe && yarn test

  run-tslint:
    <<: *defaults
    steps:
      - checkout
      - run: cat packages/*/package.json yarn.lock | shasum > .dependencies_checksum

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - attach_workspace:
          at: /home/circleci/project

      - run: yarn lint

  publish-to-npm:
    <<: *defaults
    steps:
      - checkout
      - run: cat packages/*/package.json yarn.lock | shasum > .dependencies_checksum

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Add NPM_TOKEN auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - run:
          name: Publish any updated packages to npm
          command: yarn run publish

workflows:
  run-tests:
    jobs:
      - build

      - run-tslint:
          requires:
            - build

      - run-tests:
          requires:
            - build

      - run-playground-tests:
          requires:
            - build

      - publish-to-npm:
          requires:
            - build
            - run-tests
            - run-playground-tests
            - run-tslint
          filters:
            branches:
              only: master

      - heroku/deploy-via-git:
          app-name: playground-server-staging
          requires:
            - publish-to-npm
          filters:
            branches:
              only: master

      - heroku/deploy-via-git:
          app-name: hr-bot-staging
          requires:
            - publish-to-npm
          filters:
            branches:
              only: master

      - heroku/deploy-via-git:
          app-name: ttt-bot-staging
          requires:
            - publish-to-npm
          filters:
            branches:
              only: master


