version: 2.1

orbs:
  heroku: circleci/heroku@0.0.8

defaults: &defaults
  working_directory: /home/circleci/project
  docker:
    - image: counterfactual/circleci-environment:latest

save_code: &save_code
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .git

save_dep: &save_dep
  save_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

restore_code: &restore_code
  restore_cache:
    key: code-{{ .Revision }}

restore_dep: &restore_dep
  restore_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}

jobs:
  verify-solc:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - attach_workspace:
          at: /home/circleci/project

      - run: npm i -g yarn@1.12.3 # because docker image uses 1.13.0

      - run: yarn run patch-package

      - run: "cd packages/cf-funding-protocol-contracts && yarn run verify-solc"
      - run: "cd packages/cf-adjudicator-contracts && yarn run verify-solc"
      - run: "cd packages/apps && yarn run verify-solc"

  build:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *save_code

      - <<: *restore_dep
      - run: npm i -g yarn@1.17.3 # because docker image uses 1.13.0
      - run:
          name: "yarn --frozen-lockfile"
          command: yarn --frozen-lockfile

      - run: yarn build:ci

      - <<: *save_dep

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build
            - packages/greenboard
            - packages/wallet-ui
            - packages/simple-hub-server
            - tsconfig.json
            - package.json
            - lerna.json

  run-tests:
    docker:
      - image: circleci/node:10.15.3
        environment:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_USER: postgres
          POSTGRES_DATABASE: postgres
          POSTGRES_PORT: 5432

      - image: circleci/postgres:9.6.15-alpine
        environment:
          POSTGRES_USER: postgres

    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - run: sudo npm i -g yarn@1.17.3 # because docker image uses 1.13.0

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Run Counterfactual tests
          command: yarn test:ci

  run-greenboard:
    docker:
      - image: counterfactual/greenboard-environment:latest
        environment:
          METAMASK_REPOSITORY: prototypal/metamask-extension
          METAMASK_BRANCH: develop
          WORKING_DIRECTORY: /home/circleci
          COUNTERFACTUAL_PATH: /home/circleci/project

    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - run:
          command: |
            ulimit -c unlimited
            mkdir -p /tmp/core_dumps
            cp /home/circleci/project/packages/greenboard/core /tmp/core_dumps/greenboard-core
            cp /home/circleci/project/packages/simple-hub-server/core /tmp/core_dumps/hub-core
            cp /home/circleci/project/packages/node/core /tmp/core_dumps/node-core
          when: on_fail

      - run:
          name: Symlink dependencies
          command: yarn --frozen-lockfile --ignore-engines --unsafe-perm --build-from-source

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Build Greenboard workspace and run tests
          command: yarn --ignore-engines test:e2e:ci

      - store_artifacts:
          path: /tmp/core_dumps

  run-tslint:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - attach_workspace:
          at: /home/circleci/project

      - run: npm i -g yarn@1.17.3 # because docker image uses 1.13.0

      - run: yarn lint

  ensure-updated-lockfiles:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - attach_workspace:
          at: /home/circleci/project

      - run: apt-get install -y jq # using this to mutate package.json

      - run: npm i -g yarn@1.17.3 # because docker image uses 1.13.0

      - run:
          name: Check root yarn.lock
          command: yarn --frozen-lockfile

  publish-to-npm:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - attach_workspace:
          at: /home/circleci/project

      - run: npm i -g yarn@1.17.3 # because docker image uses 1.13.0

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - run:
          name: Add NPM_TOKEN auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - run:
          name: Publish any updated packages to npm
          command: yarn run publish

workflows:
  counterfactual:
    jobs:
      - build

      - verify-solc

      - run-tslint:
          requires:
            - build

      - run-tests:
          requires:
            - build

      - run-greenboard:
          requires:
            - build
            - ensure-updated-lockfiles
            - run-tests
            - run-tslint

      - ensure-updated-lockfiles:
          requires:
            - build

      - publish-to-npm:
          requires:
            - build
            - ensure-updated-lockfiles
            - run-tests
            - run-tslint
            - run-greenboard
          filters:
            branches:
              only: master

      - heroku/deploy-via-git:
          app-name: simple-hub-server-staging
          requires:
            - publish-to-npm
          filters:
            branches:
              only: master
